In [157]:
# Install Pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [158]:
# Import Pandas
import pandas as pd

In [159]:
# Check version
pd.__version__

'2.3.3'

In [160]:
# 1. Create Dataframe
df = pd.DataFrame([1,2,3],columns=['Col_Nameprint'])
print(df)

   Col_Nameprint
0              1
1              2
2              3

In [161]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [162]:
data={
    "Name":["Abhishek","Abhay","Anuj","Aman"],
    "Age":[20,21,22,20],
    "Salary":[2000,3000,5000,9000]
}

In [163]:
df=pd.DataFrame(data)
print(df)

       Name  Age  Salary
0  Abhishek   20    2000
1     Abhay   21    3000
2      Anuj   22    5000
3      Aman   20    9000

In [164]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [165]:
# Basic DataFrame Understanding

In [166]:
df.head() # Top 5 Rows

       Name  Age  Salary
0  Abhishek   20    2000
1     Abhay   21    3000
2      Anuj   22    5000
3      Aman   20    9000

In [167]:
df.head(2) # Top 2 Rows

       Name  Age  Salary
0  Abhishek   20    2000
1     Abhay   21    3000

In [168]:
df.tail() # Bottom 5 Rows

       Name  Age  Salary
0  Abhishek   20    2000
1     Abhay   21    3000
2      Anuj   22    5000
3      Aman   20    9000

In [169]:
df.tail(2) # Bottom 2 Rows

   Name  Age  Salary
2  Anuj   22    5000
3  Aman   20    9000

In [170]:
df.shape

(4, 3)

In [171]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [172]:
df.rename(columns={'Salary':'Monthly_Salary'},inplace=True)

In [173]:
df

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000
3      Aman   20            9000

In [174]:
df1=df.rename(columns={'Salary':'Monthly_Salary'})

In [175]:
df1

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000
3      Aman   20            9000

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [177]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   20.750000     4750.000000
std     0.957427     3095.695937
min    20.000000     2000.000000
25%    20.000000     2750.000000
50%    20.500000     4000.000000
75%    21.250000     6000.000000
max    22.000000     9000.000000

In [178]:
# 3. Save and Load data from csv

In [179]:
df.to_csv('Test_data.csv',index=False) # Export DataFrame

In [180]:
load_df = pd.read_csv('Test_data.csv')  # Import DataFrame
load_df

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000
3      Aman   20            9000

In [181]:
# 4. Rows & Columns - Selection

In [182]:
# select columns
df[['Name']] # Single columns

       Name
0  Abhishek
1     Abhay
2      Anuj
3      Aman

In [183]:
df[['Name','Monthly_Salary']] # Multi columns

       Name  Monthly_Salary
0  Abhishek            2000
1     Abhay            3000
2      Anuj            5000
3      Aman            9000

In [184]:
# select rows
# loc - Label based indexing
# df.loc[df.Name=="Abhishek"]
df.loc[(df.Name=="Abhishek") & (df.Monthly_Salary>=2000)]

       Name  Age  Monthly_Salary
0  Abhishek   20            2000

In [185]:
df.loc[0:3]

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000
3      Aman   20            9000

In [186]:
# iloc - index-value based
df.iloc[0]

Name              Abhishek
Age                     20
Monthly_Salary        2000
Name: 0, dtype: object

In [187]:
df.iloc[0:3]
# [start:stop:step]

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000

In [188]:
# 4. Filter Dataframe
df

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000
3      Aman   20            9000

In [189]:
df['Age']>20

0    False
1     True
2     True
3    False
Name: Age, dtype: bool

In [190]:
df[df['Age']>=20]

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000
3      Aman   20            9000

In [191]:
df[(df['Age']>=21) & (df['Monthly_Salary']>=3000)]

    Name  Age  Monthly_Salary
1  Abhay   21            3000
2   Anuj   22            5000

In [192]:
df.where(df['Age']>20)

    Name   Age  Monthly_Salary
0    NaN   NaN             NaN
1  Abhay  21.0          3000.0
2   Anuj  22.0          5000.0
3    NaN   NaN             NaN

In [193]:
df.where(df['Age']>20,other='Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1         Abhay            21           3000
2          Anuj            22           5000
3  Not Eligible  Not Eligible   Not Eligible

In [194]:
# 6 Rows and Columns - Operations ( Add, Update, Delete)

In [195]:
df

       Name  Age  Monthly_Salary
0  Abhishek   20            2000
1     Abhay   21            3000
2      Anuj   22            5000
3      Aman   20            9000

In [196]:
# Add New Columns
df['Team']=['CEO','HR','CTO','DA']
df

       Name  Age  Monthly_Salary Team
0  Abhishek   20            2000  CEO
1     Abhay   21            3000   HR
2      Anuj   22            5000  CTO
3      Aman   20            9000   DA

In [197]:
df['Bonus']=df['Monthly_Salary']*0.2
df

       Name  Age  Monthly_Salary Team   Bonus
0  Abhishek   20            2000  CEO   400.0
1     Abhay   21            3000   HR   600.0
2      Anuj   22            5000  CTO  1000.0
3      Aman   20            9000   DA  1800.0

In [198]:
# Add New Row
df.loc[len(df)]=['ABC',21,21000,'IT',2000]
df

       Name  Age  Monthly_Salary Team   Bonus
0  Abhishek   20            2000  CEO   400.0
1     Abhay   21            3000   HR   600.0
2      Anuj   22            5000  CTO  1000.0
3      Aman   20            9000   DA  1800.0
4       ABC   21           21000   IT  2000.0

In [199]:
len(df)

5

In [200]:
# Update Value - using index name
df.loc[0,'Monthly_Salary']=95000
df

       Name  Age  Monthly_Salary Team   Bonus
0  Abhishek   20           95000  CEO   400.0
1     Abhay   21            3000   HR   600.0
2      Anuj   22            5000  CTO  1000.0
3      Aman   20            9000   DA  1800.0
4       ABC   21           21000   IT  2000.0

In [201]:
# Update Value - using columns name
df.loc[df.Name=="Abhay",'Monthly_Salary']=90000
df

       Name  Age  Monthly_Salary Team   Bonus
0  Abhishek   20           95000  CEO   400.0
1     Abhay   21           90000   HR   600.0
2      Anuj   22            5000  CTO  1000.0
3      Aman   20            9000   DA  1800.0
4       ABC   21           21000   IT  2000.0

In [202]:
# Delete Value - row and column values
df.drop(df[df.Name=='ABC'].index) # drop row, axis=0

       Name  Age  Monthly_Salary Team   Bonus
0  Abhishek   20           95000  CEO   400.0
1     Abhay   21           90000   HR   600.0
2      Anuj   22            5000  CTO  1000.0
3      Aman   20            9000   DA  1800.0

In [203]:
df.drop(4,axis=0) # index value

       Name  Age  Monthly_Salary Team   Bonus
0  Abhishek   20           95000  CEO   400.0
1     Abhay   21           90000   HR   600.0
2      Anuj   22            5000  CTO  1000.0
3      Aman   20            9000   DA  1800.0

In [204]:
df[df.Name=='ABC']

  Name  Age  Monthly_Salary Team   Bonus
4  ABC   21           21000   IT  2000.0

In [205]:
df.drop('Bonus',axis=1, inplace=True) # drop column

In [206]:
df

       Name  Age  Monthly_Salary Team
0  Abhishek   20           95000  CEO
1     Abhay   21           90000   HR
2      Anuj   22            5000  CTO
3      Aman   20            9000   DA
4       ABC   21           21000   IT

In [207]:
# df.drop(['Bonus','Team'],axis=1) # drop multiple columns

In [208]:
df

       Name  Age  Monthly_Salary Team
0  Abhishek   20           95000  CEO
1     Abhay   21           90000   HR
2      Anuj   22            5000  CTO
3      Aman   20            9000   DA
4       ABC   21           21000   IT

In [209]:
# Sort Value
df.sort_values('Monthly_Salary',ascending=False) # Descending Order

       Name  Age  Monthly_Salary Team
0  Abhishek   20           95000  CEO
1     Abhay   21           90000   HR
4       ABC   21           21000   IT
3      Aman   20            9000   DA
2      Anuj   22            5000  CTO

In [210]:
# Working with date value

In [211]:
df['DOJ']=['2024-01-01','2024-01-15','2024-03-28','2024-03-03','2024-05-02']
df

       Name  Age  Monthly_Salary Team         DOJ
0  Abhishek   20           95000  CEO  2024-01-01
1     Abhay   21           90000   HR  2024-01-15
2      Anuj   22            5000  CTO  2024-03-28
3      Aman   20            9000   DA  2024-03-03
4       ABC   21           21000   IT  2024-05-02

In [212]:
df['DOJ'].dtype

dtype('O')

In [213]:
df['DOJ']=pd.to_datetime(df['DOJ'])

In [214]:
df['DOJ'].dtype

dtype('<M8[ns]')